runtime: php55
api_version: 1
threadsafe: true
handlers:
- url: /.*
  script: main.php
env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  MYSQL_DSN: mysql:unix_socket=/cloudsql/pik-arenda:europe-west3:rent-db;dbname=rent
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: '9'
